### ISSUE TITLE
Random Crash after dying.

### ISSUE THREAD

**Issue by Akitori** [SocraticPhoenix/Randores#8]
Hiya. 

Got this crash after i died to a empowered zombie or something. 

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-104.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-71.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/23/17 4:02 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.gmail.socraticphoenix.randores.module.equip.RandoresMobEquip.onMobSpawn(RandoresMobEquip.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_RandoresMobEquip_onMobSpawn_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.world.World.func_72838_d(World.java:1203)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1059)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:160)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:202)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Random.nextInt(Random.java:388)
	at com.gmail.socraticphoenix.randores.module.equip.RandoresMobEquip.onMobSpawn(RandoresMobEquip.java:60)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_58_RandoresMobEquip_onMobSpawn_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
	at net.minecraft.world.World.func_72838_d(World.java:1203)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1059)
	at net.minecraft.world.WorldEntitySpawner.func_77192_a(WorldEntitySpawner.java:160)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:202)
	at WorldServerOF.func_72835_b(WorldServerOF.java:37)

-- Affected level --
Details:
	Level name: New World-----
	All players: 1 total; [EntityPlayerMP['TemporalWanderer'/115, l='New World-----', x=206.50, y=4.00, z=-1306.50]]
	Chunk stats: ServerChunkCache: 314 Drop: 6
	Level seed: -4393021481307236772
	Level generator: ID 01 - flat, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (205,4,-1312), Chunk: (at 13,0,0 in 12,-82; contains blocks 192,0,-1312 to 207,255,-1297), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,0,-1536 to 511,255,-1025)
	Level time: 60400 game time, 13634 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 12324 (now: true), thunder time: 4361 (now: true)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:750)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:665)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:523)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 140688536 bytes (134 MB) / 1060372480 bytes (1011 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2420 Optifine OptiFine_1.12_HD_U_C5 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2420.jar) 
	UCHIJAAAA	forge{14.21.1.2420} [Minecraft Forge] (forge-1.12-14.21.1.2420.jar) 
	UCHIJAAAA	actuallyadditions{1.12-r118} [Actually Additions] (ActuallyAdditions-1.12-r118.jar) 
	UCHIJAAAA	appliedenergistics2{rv5-alpha-3} [Applied Energistics 2] (appliedenergistics2-rv5-alpha-3.jar) 
	UCHIJAAAA	quark{r1.2-104} [Quark] (Quark-r1.2-104.jar) 
	UCHIJAAAA	autoreglib{1.3-13} [AutoRegLib] (AutoRegLib-1.3-13.jar) 
	UCHIJAAAA	codechickenlib{3.1.1.288} [CodeChicken Lib] (CodeChickenLib-1.12-3.1.1.288-universal.jar) 
	UCHIJAAAA	chickenchunks{2.4.0.70} [ChickenChunks] (ChickenChunks-1.12-2.4.0.70-universal.jar) 
	UCHIJAAAA	cyclopscore{0.10.13} [Cyclops Core] (CyclopsCore-1.12-0.10.13.jar) 
	UCHIJAAAA	colossalchests{1.6.5} [Colossal Chests] (ColossalChests-1.12-1.6.5.jar) 
	UCHIJAAAA	enderrift{2.1.9} [Ender-Rift] (EnderRift-1.12.1-2.1.9.jar) 
	UCHIJAAAA	enderstorage{1.0} [EnderStorage] (EnderStorage-1.12-2.4.0.119-universal.jar) 
	UCHIJAAAA	felling{1.3.0} [Felling] (felling-1.3.0-1.12.jar) 
	UCHIJAAAA	jei{4.7.5.88} [Just Enough Items] (jei_1.12.1-4.7.5.88.jar) 
	UCHIJAAAA	forestry{5.5.0.175} [Forestry] (forestry_1.12.1-5.5.0.175.jar) 
	UCHIJAAAA	immersiveengineering{0.12-71} [Immersive Engineering] (ImmersiveEngineering-0.12-71.jar) 
	UCHIJAAAA	immersivetech{1.2.1} [Immersive Tech] (immersivetech-1.12-1.2.1.jar) 
	UCHIJAAAA	modularrouters{1.12-3.0.1} [Modular Routers] (modular-routers-1.12-3.0.1.jar) 
	UCHIJAAAA	rafradek_tf2_weapons{1.1.11.3} [TF2 Stuff Mod] (rafradek_tf2_weapons-1.12-1.1.11.3.jar) 
	UCHIJAAAA	randores{2a7} [Randores] (Randores-2a7-shadow.jar) 
	UCHIJAAAA	torohealthmod{1.12-11} [ToroHealth Damage Indicators] (torohealth-1.12-11.jar) 
	UCHIJAAAA	veining{1.1.0} [Veining] (veining-1.1.0.jar) 
	UCHIJAAAA	jaopca{1.12-1.2.26} [Just A Ore Processing Compatibility Attempt] (JAOPCA-1.12-1.2.26.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-104.jar)
  vazkii.quark.base.asm.ClassTransformer
IELoadingPlugin (ImmersiveEngineering-0.12-71.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv5-alpha-3 for Forge 14.21.1.2412
	AE2 Integration: IC2:OFF, RC:OFF, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['TemporalWanderer'/115, l='New World-----', x=206.50, y=4.00, z=-1306.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12_HD_U_C5
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics
	OpenGlVendor: Intel
	CpuCount: 4`

**Comment by SocraticPhoenix** [comment]
I'm looking into it

**Comment by SocraticPhoenix** [comment]
This *should* be fixed in the newest release
